# Setup
title:               MintyWanna
tagline:             " First Homepage"
description:         'Written by <a>Minty WANG</a>'
url:                 https://mintywanna.github.io/
baseurl:             /home
paginate:            5
permalink:           pretty
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Minty, WANG YANFEI
  url:               https://github.com/mintyWanna
  email:             mintywangtvt@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
